config/routes.rb
Qanda::Application.routes.draw do
  get "mcoc_assets/index"

  resources :mcoc_renewals
  resources :mcoc_assets

  get "asset_other/index"

  get "asset_ude/index"

  get "static_pages/notactive"

  devise_for :users, :controllers => {:sessions => "my_sessions", :registrations => "registrations", :passwords => "passwords"}

  
  

  
  root :to => "home#index"
  devise_scope :user do
    match "/autosignin", :controller=>"my_sessions", :action=>"autosignin"
    
    match "/surveys/list_current", :to => "surveyor#list_current", :as => "list_surveys", :via => :get
    match "/surveys/questionnaire_status", :to => "surveyor#list_instanced_questionnaire_status", :as => "questionnaire_status", :via => :get
    
    match "/surveys/:survey_code/questionnaire/:response_set_code", :to => "surveyor#show_questionnaire", :as => "show_questionnaire", :via => :get
    
    match "/asset_ude/:renewals_id", :to => "asset_ude#index", :as => "asset_ude", :via => :get
    match "/asset_ude/:renewals_id/new", :to => "asset_ude#new", :as =>"asset_ude_new", :via => :post
    
    match "/asset_other/:renewals_id", :to => "asset_other#index", :as => "asset_other", :via => :get
    
    match "/surveys/:survey_code/:response_set_code/attachments/ude_report", :to => "mcoc_renewals#listudereport", :as => "ude_report"
    
    match "/surveys/:survey_code/:response_set_code/attachments/ude_report/show", :to => "mcoc_renewals#showudereport", :as => "ude_report_show", :via => :get
    
    match "/surveys/:survey_code/:response_set_code/attachments/apr_report", :to => "mcoc_renewals#listaprreport", :as => "apr_report"
    
    match "/surveys/:survey_code/:response_set_code/attachments/apr_report/show", :to => "mcoc_renewals#showaprreport", :as => "apr_report_show", :via => :get
    
    match "/surveys/:survey_code/:response_set_code/attachments/additional_doc", :to => "mcoc_assets#listadditionalassets", :as => "additional_doc"
    
    match "/surveys/:survey_code/:response_set_code/attachments/additional_doc/upload", :to => "mcoc_assets#upload", :as => "additional_doc_upload"
    
    match "/surveys/:mcoc_asset_id/:response_set_code/attachments/additional_doc/show", :to => "mcoc_assets#show", :as => "additional_asset_show", :via => :get
   
    match "/surveys/mini_survey", :to => "mcoc_mini_survey#index", :as => "mini_survey_ask", :via => :get
    
    match "/surveys/mini_survey", :to => "mcoc_mini_survey#handle_mini_survey_pref", :as => "handle_mini_survey_pref"
    
    match "/surveys/end_message", :to => "surveyor#end_message", :as => "end_message", :via => :get
    
    match "/surveys/:survey_code/:response_set_code/audit_status", :to => "surveyor#audit_status", :as => "audit_status", :via => :get

  end
  
 
  

end

app/controllers/surveyor_controller.rb
module SurveyorControllerCustomMethods
  
  def self.included(base)
    # base.send :before_filter, :require_user   # AuthLogic
    # base.send :before_filter, :login_required  # Restful Authentication
    # base.send :layout, 'surveyor_custom'
    base.send :before_filter, :obtain_audit_records_for_section, :only => :edit
    base.send :after_filter, :set_previous_section_id, :only => :edit
  end

  # Actions
  def new
    super
    @title = "Available Questionnaires"
  end
  def create
    super
  end
  def show
    super
  end
  def edit
    super
    
    @response_set_code = params[:response_set_code]
    @response_set = ResponseSet.find_by_access_code(@response_set_code)
    @response_set_id = @response_set.id
    @mcoc_user_renewals = McocUserRenewal.where(:response_set_id => @response_set_id)
    if (@mcoc_user_renewals.first != nil)
      @mcoc_renewal_id = @mcoc_user_renewals.first.mcoc_renewal_id
      session[:mcoc_renewals_id] = @mcoc_renewals_id
      @mcoc_renewal = McocRenewal.find_by_id(@mcoc_renewal_id)
      session[:project_name] = @mcoc_renewal.project_name
      session[:grantee_name] = @mcoc_renewal.grantee_name
      session[:response_set_code] = @response_set_code
      session[:originating_from_finish] = false
      prepopulate_program_name
      
      session[:quest_section] = params[:section]
      
    end
  end
  def update
    saved = false
    ActiveRecord::Base.transaction do
      @response_set = ResponseSet.find_by_access_code(params[:response_set_code], :include => {:responses => :answer}, :lock => true)
      unless @response_set.blank?
        saved = @response_set.update_attributes(:responses_attributes => ResponseSet.to_savable(params[:r]))
        @response_set.complete! if saved && params[:finish]
        saved &= @response_set.save
      end
    end
    return redirect_with_message(surveyor_finish, :notice, "Completed Questionnaire") if saved && params[:finish]

    respond_to do |format|
      format.html do
        if @response_set.blank?
          return redirect_with_message(available_surveys_path, :notice, t('surveyor.unable_to_find_your_responses'))
        else
          flash[:notice] = t('surveyor.unable_to_update_survey') unless saved
          redirect_to edit_my_survey_path(:anchor => anchor_from(params[:section]), :section => section_id_from(params[:section]))
        end
      end
      format.js do
        ids, remove, question_ids = {}, {}, []
        ResponseSet.trim_for_lookups(params[:r]).each do |k,v|
          v[:answer_id].reject!(&:blank?) if v[:answer_id].is_a?(Array)
          ids[k] = @response_set.responses.find(:first, :conditions => v, :order => "created_at DESC").id if !v.has_key?("id")
          remove[k] = v["id"] if v.has_key?("id") && v.has_key?("_destroy")
          question_ids << v["question_id"]
        end
        render :json => {"ids" => ids, "remove" => remove}.merge(@response_set.reload.all_dependencies(question_ids))
      end
    end
  end
  
  def show_questionnaire
    
    @tmp_response_set_code = params[:response_set_code]
    @tmp_response_set = ResponseSet.find_by_access_code(@tmp_response_set_code)
    @tmp_response_set_id = @tmp_response_set.id
    @mcoc_user_renewal = McocUserRenewal.find_by_response_set_id(@tmp_response_set_id)
    @tmp_mcoc_renewal_id = @mcoc_user_renewal.mcoc_renewal_id
    @tmp_user_id = session[:user_id]
    
    @mcoc_renewal = McocRenewal.find(@tmp_mcoc_renewal_id)
    @tmp_grantee_name = @mcoc_renewal.grantee_name
    @tmp_project_name = @mcoc_renewal.project_name
    
    @tmp_doc_name = @mcoc_renewal.questionnaire_doc_name
    if @tmp_doc_name.blank? 
      @questionnaire_doc_name = 0
    else
      @questionnaire_doc_name = @tmp_doc_name
    end

    @tmp_pdf_response_set = ResponseSet.find_by_access_code(@tmp_response_set_code, :include => {:responses => [:question, :answer]})
    @tmp_pdf_response_set_responses = @tmp_pdf_response_set.responses
    
    #iterate through responses
    @tmp_pdf_response_set_responses.each do |response|
      @question = response.question
    end
    
    respond_to do |format|
      format.pdf do
        questionnaire = QuestionnairePdf.new(@tmp_user_id, @tmp_mcoc_renewal_id, @tmp_response_set_code, @tmp_grantee_name, @tmp_project_name, @questionnaire_doc_name)
        if !questionnaire.nil?
          
          send_data questionnaire.render, filename: "#{@tmp_project_name}-2012-questionnaire.pdf",
                              type: "application/pdf",
                              disposition: "inline"
        end
      end
    end
    
    
  end
  
  
  def audit_status

    @audit_records = McocRenewalsDataQualityAudit.find_all_by_mcoc_renewal_id(params[:renewal_id])
    @audit_section = SurveySection.find_by_id_and_survey_id(params[:section], params[:survey_id])
    @audit_section_name = @audit_section.title
    
    @tmp_survey_access_code = session[:survey_code] 
    @tmp_response_set_code = session[:response_set_code] 
    @tmp_requested_next_section = session[:requested_next_section]
    
    @tmp_originating_from_finish = session[:originating_from_finish]
    @tmp_alternate_finish_path = session[:alternate_finish_path]
    
    @return_url_verbose = "Click here to return to the #{@audit_section_name} Section to correct."
  
  end
  
  
  #custom Action to list the current surveys
  def list_current
      #get the list of instanced (via response_sets) surveys for the current user
      #the precondition (very important) is that these have been instanced/seeded prior
      #refer to lib/tasks/instance_surveys_for_id+"N".rake
      @list_of_instanced_surveys = []
      @user_renewals_instanced_surveys = McocRenewal.joins(:mcoc_user_renewals).where(:mcoc_user_renewals => {:user_id => current_user.id}).order('grantee_name ASC, project_name ASC')
      @user_renewals_instanced_surveys.each do |user_renewals|
        @mcoc_renewals = McocUserRenewal.find_by_mcoc_renewal_id(user_renewals.id)
        @completed_date = ""
        @completed_flag = ""
        @response_set_for_user = ResponseSet.find_by_id(@mcoc_renewals.response_set_id)
        @survey = Survey.find_by_id(@response_set_for_user.survey_id)
        
        if !@response_set_for_user.completed_at.nil?
          @completed_date = @response_set_for_user.completed_at.in_time_zone("Eastern Time (US & Canada)")
        end
        if @completed_date.blank?
          @completed_flag = "No"
        else  
          @completed_flag = "Yes"
        end
        
        #stuff into the array
        @transitory_surveys = TransitoryInstancedSurvey.new(@survey.access_code, 
                      @response_set_for_user.access_code, 
                      user_renewals.grantee_name, 
                      user_renewals.project_name, @completed_flag, @completed_date)           
        @list_of_instanced_surveys << @transitory_surveys
        
      end
  end
  
  #custom action for showing a Report of Unfinished Instanced Surveys
  def list_instanced_questionnaire_status
      session[:quest_section] = 0
      @report_list = []
      @mcoc_renewals = McocRenewal.find(:all, :order => 'grantee_name ASC, project_name ASC')

      @mcoc_renewals.each do |renewals|
        @completed_date = ""
        @tmp_user_renewals = McocUserRenewal.where(:mcoc_renewal_id => renewals.id)
        @grantee_name = renewals.grantee_name
        @project_name = renewals.project_name
        if @tmp_user_renewals.first.nil?
          @response_set_access_code = "notinstanced"
          @completed_flag = "No"
          @completed_date = ""
          @survey_access_code = "notinstanced"
        else
          @response_set = ResponseSet.where(:id => @tmp_user_renewals.first.response_set_id)
          @response_set_access_code = @response_set.first.access_code
          @survey = Survey.find_by_id(@response_set.first.survey_id)
          if !@response_set.first.completed_at.nil?
            @completed_date = @response_set.first.completed_at.in_time_zone("Eastern Time (US & Canada)")
          end
          if @completed_date.blank?
            @completed_flag = "No"
          else  
            @completed_flag = "Yes"
          end
          @survey_access_code = @survey.access_code
        end
        
        #populate the model regardless of whether or not we found details 
        @transitory_report_list = TransitoryInstancedSurvey.new(@survey_access_code, 
                      @response_set_access_code, 
                      @grantee_name, 
                      @project_name, @completed_flag, @completed_date)           
        @report_list << @transitory_report_list
        
      end
    
  end
  
  
  def render_context
    
    #since we may have mustaches in place: {{recipient_name}}
    @mcoc_constants_1 = McocConstants.where(:mcoc_constant_name => 'recipient_name')
    @mcoc_constants_2 = McocConstants.where(:mcoc_constant_name => 'deadline_date')
    @mcoc_constants_3 = McocConstants.where(:mcoc_constant_name => 'recipient_email_address')
    
    MustacheContext.new(@mcoc_constants_3.first.mcoc_constant_value, @mcoc_constants_1.first.mcoc_constant_value, @mcoc_constants_2.first.mcoc_constant_value )

  end
  
  # Paths
  def section_id_from(p)
    session[:requested_next_section] = params[:section]
    p.respond_to?(:keys) ? p.keys.first : p
  end

  def anchor_from(p)
    p.respond_to?(:keys) && p[p.keys.first].respond_to?(:keys) ? p[p.keys.first].keys.first : nil
  end
  
  def surveyor_index
    # most of the above actions redirect to this method
    super # available_surveys_path
  end
  def surveyor_finish
    # the update action redirects to this method if given params[:finish]
    #super # available_surveys_path

    @tmp_response_set_code = session[:response_set_code]
    @tmp_response_set = ResponseSet.find_by_access_code(@tmp_response_set_code)
    @tmp_survey = Survey.find(@tmp_response_set.survey_id)

    #only do this with the Monitoring Questionnaire related items

app/views/surveyor/audit_status.html.haml
#surveyor
  %br
  #audit_list_head
    Questionnaire Submission Summary
  #audit_list_subpara
    - @alternate_text_here = "here to continue."
    Missing information is displayed in red. Click on a section name to correct, or click 
    - if @tmp_alternate_finish_path == "end_message"
      = link_to @alternate_text_here, end_message_path
    - if @tmp_alternate_finish_path == "mini_survey_ask"
      = link_to @alternate_text_here, mini_survey_ask_path
    Please remember that if you do not provide all of the required information, your Questionnaire will be considered incomplete.
  #audit_list
    %ul
      - unless @audit_records.empty?
        - @first_time = true
        - @audit_records.each do |audit|
          - if @first_time
            - @working_section_name = audit.section_name
            - @first_time = false
            %div.section_name 
              = link_to "Section: #{@working_section_name}", edit_my_survey_path(:survey_code => @tmp_survey_access_code, :response_set_code => @tmp_response_set_code, :section => audit.section_id)
          - else
            - if @working_section_name == audit.section_name
            - else
              %div.section_name 
                = link_to "Section: #{audit.section_name}", edit_my_survey_path(:survey_code => @tmp_survey_access_code, :response_set_code => @tmp_response_set_code, :section => audit.section_id)
                - @working_section_name = audit.section_name
          %div.section_key_info
            %ul
            - @work_audit_key = audit.audit_key
            - if @work_audit_key == "Complete."
              %li.complete
                = @work_audit_key
            - else
              %li
                = @work_audit_key
        #audit_closure_message

         

app/views/surveyor/end_message.html.haml
#surveyor
  - unless (types = flash.keys.select{|k| [:notice, :error, :warning].include?(k)}).blank?
    .surveyor_flash
      = flash_messages(types)
      .close
  %br
  You have reached the end of the Questionnaire. Please close this window.

app/views/surveyor/list_current.html.haml
#surveyor
  - unless (types = flash.keys.select{|k| [:notice, :error, :warning].include?(k)}).blank?
    .surveyor_flash
      = flash_messages(types)
      .close
  .survey_title= '2012 Monitoring and Evaluation Questionnaire'
  %br
  #survey_list
    %ul
      - unless @list_of_instanced_surveys.empty?
      - @first_time = true
        - @list_of_instanced_surveys.each do |survey|
          %li
            = form_tag(edit_my_survey_path(:survey_code => survey.survey_access_code, :response_set_code => survey.response_access_code)) do 
              = hidden_field_tag :surveyor_javascript_enabled, false
            
              %div#survey_list_details
                - if @first_time
                  - @working_grantee_name = survey.grantee_name
                  - @first_time = false
                  %div.grantee_name 
                    = @working_grantee_name
                - else
                  - if @working_grantee_name == survey.grantee_name
                  - else
                    %div.grantee_name 
                      = survey.grantee_name
                      
                %div.project_name
                  = link_to survey.project_name, edit_my_survey_path(:survey_code => survey.survey_access_code, :response_set_code => survey.response_access_code, :section => "1", :first_visit => "1"), :target => "_blank" 
                %div.project_name_links
                  = link_to '(View PDF)', show_questionnaire_path(:survey_code => survey.survey_access_code, :response_set_code => survey.response_access_code, format: "pdf")
                  - if survey.completed_flag == "No"
                    Completed? #{survey.completed_flag} 
                  - else
                    Completed? #{survey.completed_flag} - #{survey.completed_date}
              - @working_grantee_name = survey.grantee_name
      - else
        %li
          No surveys

:javascript
  $(document).ready(function() {
    $("input#surveyor_javascript_enabled").val(true);
  });

app/views/surveyor/list_instanced_questionnaire_status.html.haml
#surveyor
  - unless (types = flash.keys.select{|k| [:notice, :error, :warning].include?(k)}).blank?
    .surveyor_flash
      = flash_messages(types)
      .close
  .survey_title= '2012 Monitoring and Evaluation Questionnaire - Status Report'
  %br
  #survey_list
    %ul
      - unless @report_list.empty?
      - @first_time = true
        - @report_list.each do |report|
          %li
            = form_tag(edit_my_survey_path(:survey_code => report.survey_access_code, :response_set_code => report.response_access_code)) do 
              = hidden_field_tag :surveyor_javascript_enabled, false
              %div#survey_list_details
                - if @first_time
                  - @working_grantee_name = report.grantee_name
                  - @first_time = false
                  %div.grantee_name 
                    = @working_grantee_name
                - else
                  - if @working_grantee_name == report.grantee_name
                  - else
                    %div.grantee_name 
                      = report.grantee_name
                      
                %div.project_name
                  - if report.survey_access_code == "notinstanced"
                    #{report.project_name} (not yet instanced)
                  - else
                    = link_to report.project_name, edit_my_survey_path(:survey_code => report.survey_access_code, :response_set_code => report.response_access_code, :section => "1") 
                %div.project_name_links
                  - if report.survey_access_code != "notinstanced"
                    = link_to '(View PDF)', show_questionnaire_path(:survey_code => report.survey_access_code, :response_set_code => report.response_access_code, format: "pdf")
                  - if report.completed_flag == "No"
                    Completed? #{report.completed_flag} 
                  - else
                    Completed? #{report.completed_flag} - #{report.completed_date}
              - @working_grantee_name = report.grantee_name
              
      - else
        %li
          No Questionnaire Status to Show.

:javascript
  $(document).ready(function() {
    $("input#surveyor_javascript_enabled").val(true);
  });

app/views/surveyor/new.html.haml
#surveyor
  - unless (types = flash.keys.select{|k| [:notice, :error, :warning].include?(k)}).blank?
    .surveyor_flash
      = flash_messages(types)
      .close
  .survey_title= t('surveyor.take_these_surveys')
  %br
  
  #survey_list
    %ul
      - unless @surveys.empty?
        - @surveys.each do |survey|
          %li
            = form_tag(take_survey_path(:survey_code => survey.access_code)) do 
              = hidden_field_tag :surveyor_javascript_enabled, false              

              = survey.title
              &nbsp;
              = submit_tag( t('surveyor.take_it') )
      - else
        %li
          No surveys

:javascript
  $(document).ready(function() {
    $("input#surveyor_javascript_enabled").val(true);
  });

app/views/surveyor/show.html.haml
#surveyor
  - unless (types = flash.keys.select{|k| [:notice, :error, :warning].include?(k)}).blank?
    .surveyor_flash
      = flash_messages(types)
      .close
  = semantic_form_for(@response_set, :as => :r, :url => update_my_survey_path, :html => {:id => "survey_form", :class => @survey.custom_class}) do |f|
    .survey_title= @survey.title
    - @survey.sections.each do |section|
      = div_for section do
        %span.title= strip_tags(section.title)
        - group_questions = []
        - answered_questions = []
        - label = nil
        - answered_count = 0
        - (questions = section.questions).each_with_index do |q, i|
          - if q.part_of_group?
            - group_questions << q # gather up the group questions
            - unless @response_set.responses.where( :question_id => q.id).empty?
              - answered_questions << q
              - answered_count = answered_count + 1
            - if (i+1 >= questions.size) or (q.question_group_id != questions[i+1].question_group_id) # this is the last question of the section, or the group
              - if answered_questions.length > 0 # there are answered questions in this section or group
                - g = q.question_group
                - renderer = g.renderer
                
                - unless label.blank?
                  = render q.custom_renderer || "/partials/question", :q => label, :f => f, :disableFlag => true
                  - label = nil
                = f.inputs q_text(g), :id => "g_#{g.id}", :class => "g_#{renderer} #{g.css_class(@response_set)}" do
                  %li.help= g.help_text
                  - case renderer
                    - when :grid
                      %li
                        %table
                          %col.pre
                          - group_questions.first.answers.each do |a| 
                            %col{:class => cycle("odd", "even")}
                          %col.post
                          %tbody
                            - group_questions.each_slice(10) do |ten_questions| # header row every 10
                              %tr
                                %th &nbsp;
                                - ten_questions.first.answers.each do |a|
                                  %th= a_text(a)
                                %th &nbsp;
                              - ten_questions.each_with_index do |q, j|
                                %tr{:id => "q_#{q.id}", :class => "q_#{renderer} #{q.css_class(@response_set)}"}
                                  - if q.pick == "one"
                                    - r = response_for(@response_set, q, nil, g)
                                    - j = response_idx  # increment the response index since the answer partial skips for q.pick == one
                                  %th= q.split_text(:pre)
                                  - q.answers.each do |a|
                                    %td= render a.custom_renderer || '/partials/answer', :g => g, :q => q, :a => a, :f => f, :disableFlag => true
                                  %th= q.split_text(:post)
                    - when :repeater
                      - (@response_set.count_group_responses(group_questions) + 1).times do |rg|
                        %li
                          - group_questions.each do |q|
                            = render q.custom_renderer || "/partials/question", :g => g, :rg => rg, :q => q, :f => f, :disableFlag => true
                    - else # :inline
                      - answered_questions.each do |q|
                        = render q.custom_renderer || "/partials/question", :g => g, :q => q, :f => f, :disableFlag => true         
              
              - group_questions = []
              - answered_questions = []
          - else 
            - if q.display_type == 'label'
              - label = q
            - unless @response_set.responses.where( :question_id => q.id).empty?
              - unless label.blank?
                = render q.custom_renderer || "/partials/question", :q => label, :f => f, :disableFlag => true
                - label = nil
              = render q.custom_renderer || "/partials/question", :q => q, :f => f, :disableFlag => true
              - answered_count = answered_count + 1
          - if (i+1 >= questions.size) and (answered_count == 0)
            #{"--- No data ---"}
          