config/routes.rb
Qanda::Application.routes.draw do
  get "mcoc_assets/index"

  resources :mcoc_renewals
  resources :mcoc_assets

  get "asset_other/index"

  get "asset_ude/index"

  get "static_pages/notactive"

  devise_for :users, :controllers => {:sessions => "my_sessions", :registrations => "registrations", :passwords => "passwords"}

  
  

  
  root :to => "home#index"
  devise_scope :user do
    match "/autosignin", :controller=>"my_sessions", :action=>"autosignin"
    
    match "/surveys/list_current", :to => "surveyor#list_current", :as => "list_surveys", :via => :get
    match "/surveys/questionnaire_status", :to => "surveyor#list_instanced_questionnaire_status", :as => "questionnaire_status", :via => :get
    
    match "/surveys/:survey_code/questionnaire/:response_set_code", :to => "surveyor#show_questionnaire", :as => "show_questionnaire", :via => :get
    
    match "/asset_ude/:renewals_id", :to => "asset_ude#index", :as => "asset_ude", :via => :get
    match "/asset_ude/:renewals_id/new", :to => "asset_ude#new", :as =>"asset_ude_new", :via => :post
    
    match "/asset_other/:renewals_id", :to => "asset_other#index", :as => "asset_other", :via => :get
    
    match "/surveys/:survey_code/:response_set_code/attachments/ude_report", :to => "mcoc_renewals#listudereport", :as => "ude_report"
    
    match "/surveys/:survey_code/:response_set_code/attachments/ude_report/show", :to => "mcoc_renewals#showudereport", :as => "ude_report_show", :via => :get
    
    match "/surveys/:survey_code/:response_set_code/attachments/apr_report", :to => "mcoc_renewals#listaprreport", :as => "apr_report"
    
    match "/surveys/:survey_code/:response_set_code/attachments/apr_report/show", :to => "mcoc_renewals#showaprreport", :as => "apr_report_show", :via => :get
    
    match "/surveys/:survey_code/:response_set_code/attachments/additional_doc", :to => "mcoc_assets#listadditionalassets", :as => "additional_doc"
    
    match "/surveys/:survey_code/:response_set_code/attachments/additional_doc/upload", :to => "mcoc_assets#upload", :as => "additional_doc_upload"
    
    match "/surveys/:mcoc_asset_id/:response_set_code/attachments/additional_doc/show", :to => "mcoc_assets#show", :as => "additional_asset_show", :via => :get
   
    match "/surveys/mini_survey", :to => "mcoc_mini_survey#index", :as => "mini_survey_ask", :via => :get
    
    match "/surveys/mini_survey", :to => "mcoc_mini_survey#handle_mini_survey_pref", :as => "handle_mini_survey_pref"
    
    match "/surveys/end_message", :to => "surveyor#end_message", :as => "end_message", :via => :get
    
    match "/surveys/:survey_code/:response_set_code/audit_status", :to => "surveyor#audit_status", :as => "audit_status", :via => :get

  end
  
 
  

end

app/models/mcoc_renewal.rb
class McocRenewal < ActiveRecord::Base
  
  has_many :mcoc_assets
  has_many :mcoc_user_renewals
  
  attr_accessible :grantee_name, :project_name, :component, :attachment_ude, :attachment_ude_file_name, :mcoc_assets_attributes, 
                  :grantee_folder_id, :project_folder_id, 
                  :hud_report_folder_id, :questionnaire_folder_id,:supporting_doc_folder_id, :doc_name, :questionnaire_doc_name,
                  :attachment_apr, :apr_report_folder_id, :apr_report_doc_name
  
  accepts_nested_attributes_for :mcoc_assets, :allow_destroy => true
  
  has_attached_file :attachment_ude,
                :url => "/ude_report/:grantee_name/:project_name/:basename.:extension",    
                :path => ":rails_root/2012_Renewals_Assets/ude_report/:grantee_name/:project_name/:basename.:extension"
 
  has_attached_file :attachment_apr,
                :url => "/apr_report/:grantee_name/:project_name/:basename.:extension",    
                :path => ":rails_root/2012_Renewals_Assets/apr_report/:grantee_name/:project_name/:basename.:extension"
 

end

app/models/mcoc_renewals.rb
class McocRenewals < ActiveRecord::Base
  
  has_many :mcoc_assets
  
  attr_accessible :grantee_name, :project_name, :component, :attachment_ude, :mcoc_assets_attributes, 
                  :grantee_folder_id, :project_folder_id,
                  :hud_report_folder_id, :questionnaire_folder_id,:supporting_doc_folder_id, :doc_name, :questionnaire_doc_name,
                  :attachment_apr, :apr_report_folder_id, :apr_report_doc_name
  
  accepts_nested_attributes_for :mcoc_assets, :allow_destroy => true
  
  has_attached_file :attachment_ude,
                :url => "/ude_report/:grantee_name/:project_name/:basename.:extension",    
                :path => ":rails_root/2012_Renewals_Assets/ude_report/:grantee_name/:project_name/:basename.:extension"
 
  has_attached_file :attachment_apr,
                :url => "/apr_report/:grantee_name/:project_name/:basename.:extension",    
                :path => ":rails_root/2012_Renewals_Assets/apr_report/:grantee_name/:project_name/:basename.:extension"
 

end

app/controllers/mcoc_renewals_controller.rb
class McocRenewalsController < ApplicationController
  before_filter :authenticate_user! #authenticate for users before any methods is called

  def index
    @mcoc_renewals = McocRenewal.all
  end

  def new
    @mcoc_renewals = McocRenewal.new
  end

  def create
    @mcoc_renewals = McocRenewal.new(params[:mcoc_renewals])
    if @mcoc_renewals.save
      redirect_to mcoc_renewals_url, :notice => "Successfully created mcoc renewals."
    else
      render :action => 'new'
    end
  end

  def edit
    @mcoc_renewals = McocRenewal.find(params[:id])
  end

  def update
    @mcoc_renewal = McocRenewal.find(params[:id])
    
    @mcoc_group_id = Rails.configuration.liferaymcocgroupid
    @hud_report_folder_id = @mcoc_renewal.hud_report_folder_id
    @apr_report_folder_id = @mcoc_renewal.apr_report_folder_id
    @doc_name = @mcoc_renewal.doc_name
    @apr_report_doc_name = @mcoc_renewal.apr_report_doc_name
    
    @liferay_ws = LiferayDocument.new
    
    @delete_flag = params[:clear_attachment_ude]
    if @delete_flag == "1" 
       @liferay_ws_result = @liferay_ws.delete(@mcoc_group_id, @hud_report_folder_id, @doc_name)
       @mcoc_renewal.update_attributes(:doc_name => nil)
       @mcoc_renewal.update_attribute(:attachment_ude, nil)
       redirect_to(session[:return_to] || default)
       session[:return_to] = nil
    else
      
      @delete_flag = params[:clear_attachment_apr]
      
      if @delete_flag == "1" 
         @liferay_ws_result = @liferay_ws.delete(@mcoc_group_id, @apr_report_folder_id, @apr_report_doc_name)
         @mcoc_renewal.update_attributes(:apr_report_doc_name => nil)
         @mcoc_renewal.update_attribute(:attachment_apr, nil)
         redirect_to(session[:return_to] || default)
         session[:return_to] = nil
      else
      
        @tmp_report_type = params[:mcoc_renewal][:report_type]
        
        if @tmp_report_type == "ude_report"
          @uploaded_file = params[:mcoc_renewal][:attachment_ude].tempfile
          @uploaded_file_name_extension = params[:mcoc_renewal][:attachment_ude].original_filename.split('.').last
          @uploaded_file_name = "UDE Completeness Report - #{session[:project_name]}.#{@uploaded_file_name_extension}"
          @external_doclib_folder_id = @hud_report_folder_id
          @external_doc_name = @doc_name
        else
          @uploaded_file = params[:mcoc_renewal][:attachment_apr].tempfile
          @uploaded_file_name_extension = params[:mcoc_renewal][:attachment_apr].original_filename.split('.').last
          @uploaded_file_name = "APR Report - #{session[:project_name]}.#{@uploaded_file_name_extension}"
          @external_doclib_folder_id = @apr_report_folder_id
          @external_doc_name = @apr_report_doc_name
        end
      
        @uploaded_file_desc = ""
        @tmp = File.open(@uploaded_file, 'rb').read
        @base64_uploaded_file = Base64.encode64(@tmp)
      
      
        if @external_doc_name.blank?
          
          @added_result = @liferay_ws.add(@mcoc_group_id, @external_doclib_folder_id, @uploaded_file_name, @uploaded_file_desc, @base64_uploaded_file)
          #update the given mcoc_renewal record with the uuid that we just generated due to the addition of the document in the doclib.
          @added_doc_name = @added_result[:doc_name]
          @added_primary_key = @added_result[:primary_key]
          #call the webservice that applies specific permissions on the file (primary_ley) just added to the document library:
          @liferay_ws_permission = LiferayPermission.new
          @company_id = Rails.configuration.liferaycompanyid
          @role_id = Rails.configuration.liferaymcocmonitoringcmterole
          @name = Rails.configuration.liferaywsdldlfileentryname
          @action_ids = Rails.configuration.liferaymcocmonitoringcmteroleactionidsfile
          @liferay_ws_permission.add_for_mcoc_user(@mcoc_group_id, @company_id, @name, @added_primary_key, @role_id, @action_ids)
          #and lastly, update the mcoc_renewal contoller with the doc_name we got back from the ws "add" call above...
          if @tmp_report_type == "ude_report"
            @mcoc_renewal.update_attributes(:doc_name => @added_doc_name)
          else
            @mcoc_renewal.update_attributes(:apr_report_doc_name => @added_doc_name)
          end 
        else
          #since we most likely have an existing file already uploaded, we need to update the existing document.
          #To be extra careful, we will check that it exists in the doclib, then issue the call to update the doclib entry
          @liferay_ws_result = @liferay_ws.get(@mcoc_group_id, @external_doclib_folder_id, @external_doc_name)
          if @liferay_ws_result == "found"
            #we need to update, as opposed to add
            @liferay_ws.update(@mcoc_group_id, @external_doclib_folder_id, @external_doc_name, @uploaded_file_name, @uploaded_file_desc, @base64_uploaded_file)
          end
        end
      
        if @mcoc_renewal.update_attributes(params[:mcoc_renewal])
          redirect_to(session[:return_to] || default)
          session[:return_to] = nil
        end
  
      end
      
    end
  end
  
  def listudereport
    @response_set_code = params[:response_set_code]
    @response_set = ResponseSet.find_by_access_code(@response_set_code)
    @response_set_id = @response_set.id
    @mcoc_user_renewals = McocUserRenewal.where(:response_set_id => @response_set_id)
    @mcoc_renewals_id = @mcoc_user_renewals.first.mcoc_renewal_id
    @mcoc_renewal = McocRenewal.find_by_id(@mcoc_renewals_id)
    session[:mcoc_renewals_id] = @mcoc_renewal.id
    session[:return_to] = request.fullpath
    respond_to do |format|
        format.html # 
        format.json { render json: @mcoc_renewals }
    end
  end
  
  def listaprreport
    @response_set_code = params[:response_set_code]
    @response_set = ResponseSet.find_by_access_code(@response_set_code)
    @response_set_id = @response_set.id
    @mcoc_user_renewals = McocUserRenewal.where(:response_set_id => @response_set_id)
    @mcoc_renewals_id = @mcoc_user_renewals.first.mcoc_renewal_id
    @mcoc_renewal = McocRenewal.find_by_id(@mcoc_renewals_id)
    session[:mcoc_renewals_id] = @mcoc_renewal.id
    session[:return_to] = request.fullpath
    respond_to do |format|
        format.html # 
        format.json { render json: @mcoc_renewals }
    end
  end
  
  
  def showudereport
    @tmp_mcoc_renewal_id = session[:mcoc_renewals_id]
    @mcoc_renewal = McocRenewal.find(@tmp_mcoc_renewal_id)
    send_file @mcoc_renewal.attachment_ude.path, :type => @mcoc_renewal.attachment_ude_content_type, :disposition => 'inline' 
  end
  def showaprreport
    @tmp_mcoc_renewal_id = session[:mcoc_renewals_id]
    @mcoc_renewal = McocRenewal.find(@tmp_mcoc_renewal_id)
    send_file @mcoc_renewal.attachment_apr.path, :type => @mcoc_renewal.attachment_apr_content_type, :disposition => 'inline' 
  end

  
end

app/helpers/mcoc_renewals_helper.rb
module McocRenewalsHelper
end

app/views/mcoc_renewals/_form.html.erb
<%= form_for @mcoc_renewals do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :grantee_name %><br />
    <%= f.text_field :grantee_name %>
  </p>
  <p>
    <%= f.label :project_name %><br />
    <%= f.text_field :project_name %>
  </p>
  <p>
    <%= f.label :component %><br />
    <%= f.text_field :component %>
  </p>
  <p>
    <%= f.label :attachment_ude_file_name %><br />
    <%= f.text_field :attachment_ude_file_name %>
  </p>
  <p>
    <%= f.label :attachment_ude_content_type %><br />
    <%= f.text_field :attachment_ude_content_type %>
  </p>
  <p>
    <%= f.label :attachment_ude_file_size %><br />
    <%= f.number_field :attachment_ude_file_size %>
  </p>
  <p>
    <%= f.label :attachment_ude_updated_at %><br />
    <%= f.datetime_select :attachment_ude_updated_at %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/mcoc_renewals/edit.html.erb
<% title "Edit Mcoc Renewals" %>

<%= render 'form' %>

app/views/mcoc_renewals/index.html.erb
<% title "Mcoc Renewals" %>

<table>
  <tr>
    <th>Grantee Name</th>
    <th>Project Name</th>
    <th>Component</th>
    <th>Attachment Ude File Name</th>
    <th>Attachment Ude Content Type</th>
    <th>Attachment Ude File Size</th>
    <th>Attachment Ude Updated At</th>
  </tr>
  <% for mcoc_renewals in @mcoc_renewals %>
    <tr>
      <td><%= mcoc_renewals.grantee_name %></td>
      <td><%= mcoc_renewals.project_name %></td>
      <td><%= mcoc_renewals.component %></td>
      <td><%= mcoc_renewals.attachment_ude_file_name %></td>
      <td><%= mcoc_renewals.attachment_ude_content_type %></td>
      <td><%= mcoc_renewals.attachment_ude_file_size %></td>
      <td><%= mcoc_renewals.attachment_ude_updated_at %></td>
      <td><%= link_to "Edit", edit_mcoc_renewal_path(mcoc_renewals) %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Mcoc Renewals", new_mcoc_renewal_path %></p>

app/views/mcoc_renewals/listaprreport.html.erb
<%= form_for @mcoc_renewal, :html => { :multipart => true, :name => 'mcoc_renewal' }, :remote => true do |f| %>
	<% if @mcoc_renewal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mcoc_renewal.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @mcoc_renewal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @mcoc_renewal.attachment_apr.exists? %>
	<div id="apr_current_report" class="field">
		<%= link_to "View APR Report", apr_report_show_path(f), :target => "_blank" %>
		<%= check_box_tag "clear_attachment_apr"   %>
		<%= f.label "Delete" %>
    </div>
  <% else %>
  <% end %>
  <div id="apr_upload_section">
	 <div id="apr_upload_text">
	   <p>Instructions: Browse to your APR Report, select the file, then click 'Upload'. 
	    <% if @mcoc_renewal.attachment_apr.exists? %> 
	      Uploading a new report will overwrite the existing report.
		<% end %>
	 </p>
	</div>
	 <div class="field">
	   <%= f.file_field :attachment_apr %>
	 </div>
	 <%= f.hidden_field "report_type", :value => "apr_report" %>
	 <div class="actions">
	   <%= f.submit 'Upload', :disable_with => 'Uploading ...' %>
	 </div>
  </div>
<% end %>

app/views/mcoc_renewals/listudereport.html.erb
<%= form_for @mcoc_renewal, :html => { :multipart => true, :name => 'mcoc_renewal' }, :remote => true do |f| %>
	<% if @mcoc_renewal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mcoc_renewal.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @mcoc_renewal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @mcoc_renewal.attachment_ude.exists? %>
	<div id="ude_current_report" class="field">
		<%= link_to "View UDE Completeness Report", ude_report_show_path(f), :target => "_blank" %>
		<%= check_box_tag "clear_attachment_ude"   %>
		<%= f.label "Delete" %>
    </div>
  <% else %>
  <% end %>
  <div id="ude_upload_section">
	 <div id="ude_upload_text">
	   <p>Instructions: Browse to your UDE Completeness Report, select the file, then click 'Upload'. 
	    <% if @mcoc_renewal.attachment_ude.exists? %> 
	      Uploading a new report will overwrite the existing report.
		<% end %>
	 </p>
	</div>
	 <div class="field">
	   <%= f.file_field :attachment_ude %>
	 </div>
	<%= f.hidden_field "report_type", :value => "ude_report"%>
	 <div class="actions">
	   <%= f.submit 'Upload', :disable_with => 'Uploading ...' %>
	 </div>
  </div>
<% end %>

<!--<div id="loading_ude" style="display:none;">
	<img src="/assets/ajax-loader.gif" alt="Loading...">
</div>
-->

app/views/mcoc_renewals/new.html.erb
<% title "New Mcoc Renewals" %>

<%= render 'form' %>

<p><%= link_to "Back to List", mcoc_renewals_path %></p>